#!/bin/sh
echo

config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}

# I call this "Not Being Lazy"
echo "You aren't allowed to bootstrap until you've checked the file!"
echo "Go to ${config_home}/yadm/bootstrap and verify that everything looks fine =|:)"
echo "It's a pretty simple shell script, so you shouldn't have much trouble."
echo
# Can you tell what this line does?
exit 1

# https://stackoverflow.com/questions/29436275/how-to-prompt-for-yes-or-no-in-bash
yes_or_no() {
	local yn
	while true; do
	    read -p "$* [y/n]: " yn
		case $yn in
			[Yy]*) return 0  ;;
			[Nn]*) echo "Aborted" ; return  1 ;;
		esac
	done
}

# Now that you're here, edit the rest of the file to your liking and make sure you're comfortable
# with everything that's happening below.
cd "$HOME"

if yes_or_no "Install programs in installs.txt?"; then
	sudo pacman -Syu $(cat installs.txt);
fi
echo

# You can't do this unless you're me, on account of it's my encrypted data, so I'd advise declining
if yes_or_no "Decrypt files? (Only works if you're me)"; then
	yadm decrypt
fi
echo

# Do you want my neovim config? (kickstart.nvim)
if yes_or_no "Init submodules? (neovim config)"; then
	yadm submodule update --recursive --init
fi
echo

echo "Services:"

if yes_or_no "Enable greetd to autostart sway?"; then
	sudo systemctl enable greetd.service
	sudo cp -r ~/.root-config/etc/greetd /etc/
fi

if yes_or_no "Enable sshd?"; then
	sudo systemctl enable sshd.service
fi

if yes_or_no "Configure ufw? (my setup, beware)"; then
	sudo systemctl enable iptables.service
	sudo systemctl enable ufw.service
	sudo ufw default deny

	# open lan
	sudo ufw allow from 192.168.0.0/24
	# ssh
	sudo ufw limit ssh
	sudo cp -r ~/.root-config/etc/ufw/applications.d/kdeconnect /etc/ufw/applications.d/
	sudo ufw allow kdeconnect

	sudo cp -r ~/.root-config/etc/ufw/applications.d/teamspeak3 /etc/ufw/applications.d/

	sudo ufw enable
	sudo ufw status
fi

if yes_or_no "Set default shell to zsh?"; then
	chsh -s /bin/zsh
fi

if yes_or_no "Install oh-my-zsh?"; then
	sh -c \
	"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
	"" --skip-chsh --keep-zshrc
fi
echo

echo "You must reboot for changes to take effect."
if yes_or_no "Reboot now?"; then
	reboot
fi
echo

echo "Have fun with your new system!"
exit 0
