#!/bin/sh
echo

CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}

# I call this "Not Being Lazy"
echo "You aren't allowed to bootstrap until you've checked the file!"
echo "Go to $CONFIG_HOME/yadm/bootstrap and verify that everything looks fine =|:)"
echo "It's a pretty simple shell script, so you shouldn't have much trouble."
# Can you tell what this line does?
exit 1

# https://stackoverflow.com/questions/29436275/how-to-prompt-for-yes-or-no-in-bash
function yes_or_no {
	local yn
	while true; do
	    read -p "$* [y/n]: " yn
		case $yn in
			[Yy]*) return 0  ;;
			[Nn]*) echo "Aborted" ; return  1 ;;
		esac
	done
}

# Now that you're here, edit the rest of the file to your liking and make sure you're comfortable
# with everything that's happening below.
cd "$HOME"

yes_or_no "Install programs in installs.txt?" && \
	sudo pacman -Syu $(cat install.txt)
echo

# You can't do this unless you're me, on account of it's my encrypted data, so I'd advise declining
yes_or_no "Decrypt files? (Only works if you're me)" && \
	yadm decrypt
echo

# Do you want my neovim config? (kickstart.nvim)
yes_or_no "Init submodules? (neovim config)" && \
	yadm submodule update --recursive --init
echo

echo "Services:"

yes_or_no "Enable greetd to autostart sway?" && {
	sudo systemctl enable greetd
	sudo cp -r ~/.root-config/etc/greetd /etc/
}

yes_or_no "Set default shell to zsh?" && \
	chsh -s /bin/zsh

yes_or_no "Install oh-my-zsh?" && \
	sh -c \
	"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
	"" --skip-chsh --keep-zshrc
echo

echo "You must reboot for changes to take effect."
yes_or_no "Reboot now?" && reboot
echo

echo "Have fun with your new system!"
exit 0
