set -g allow-passthrough on

## prefix to C-Space
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# mouse stuff I guess
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'tmux-pluginx/tmux-continuum'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
