#!/bin/sh

#while true; do
    # pick a background from the backgrounds directory  and set it
    background="$(fd . ~/Pictures/backgrounds | sort -R | tail -1)"
    swww img "$background"

#    sleep 300
#done
